{{- if .Values.ingress.enabled -}}
{{- if eq .Values.ingress.controllerName "openshiftRouter" -}}
{{- $serviceName := include "oauth2-proxy.fullname" . -}}
{{- $servicePort := .Values.service.portNumber -}}
{{- $ingressPath := .Values.ingress.path -}}
{{- $ingressPathType := .Values.ingress.pathType -}}
{{- $extraPaths := .Values.ingress.extraPaths -}}
apiVersion: {{ include "capabilities.ingress.apiVersion" . }}
kind: Ingress
metadata:
  labels:
    app: {{ template "oauth2-proxy.name" . }}
    {{- include "oauth2-proxy.labels" . | indent 4 }}
{{- if .Values.ingress.labels }}
{{ toYaml .Values.ingress.labels | indent 4 }}
{{- end }}
  name: {{ template "oauth2-proxy.fullname" . }}
  namespace: {{ template "oauth2-proxy.namespace" $ }}
  annotations:
    haproxy-ingress.github.io/headers: |
      X-Forwarded-Prefix: {{ $ingressPath }}
  {{- range $host := .Values.ingress.hosts }}
      X-Forwarded-Host: {{ tpl $host $ | quote }}
  {{- end }}
      X-Forwarded-Port: 443
      X-Forwarded-Proto: https
  {{- with .Values.global.cp.resources.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.ingress.annotations }}
    {{ toYaml . | indent 4 }}
  {{- end }}
spec:
  ingressClassName: haproxy
  rules:
    {{- range $host := .Values.ingress.hosts }}
    - host: {{ tpl $host $ | quote }}
      http:
        paths:
{{- if $extraPaths }}
{{ toYaml $extraPaths | indent 10 }}
{{- end }}
          - path: {{ $ingressPath }}
            {{- if eq "true" ( include "ingress.supportsPathType" $ ) }}
            pathType: {{ $ingressPathType }}
            {{- end }}
            backend: {{- include "ingress.backend" ( dict "serviceName" $serviceName "servicePort" $servicePort "context" $ )  | nindent 14 }}
    {{- end -}}
  {{- if .Values.ingress.tls }}
  tls:
{{ tpl (toYaml .Values.ingress.tls) $ | indent 4 }}
  {{- end -}}
{{- end -}}
{{- end -}}
