# Copyright © 2023. Cloud Software Group, Inc.
# This file is subject to the license terms contained
# in the license file that is distributed with this file.

{{ if eq .Values.publicApi.ingress.controllerName "nginx" -}}
{{- $fullName := include "flogoprovisioner.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: {{ .Release.Namespace }}-{{ $fullName }}-auth-errors@kubernetescrd,{{ .Release.Namespace }}-{{ $fullName }}-auth@kubernetescrd,{{ .Release.Namespace }}-{{ $fullName }}-rewrite@kubernetescrd
    external-dns.alpha.kubernetes.io/target: {{ .Values.publicApi.ingress.nginx.fqdn }}
  name: {{ $fullName }}-public-nginx
spec:
  ingressClassName: traefik
  rules:
  - host: {{ .Values.publicApi.ingress.nginx.fqdn }}
    http:
      paths:
      - backend:
          service:
            name: {{ $fullName }}
            port:
              number: {{ $.Values.publicApiService.targetPort }}
        path: {{ .Values.publicApi.ingress.nginx.pathPrefix }}/
        pathType: Prefix
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ $fullName }}-auth
spec:
  forwardAuth:
    address: https://{{ .Values.publicApi.ingress.nginx.fqdn }}{{ .Values.publicApi.ingress.nginx.pathPrefix }}/oauth2
    trustForwardHeader: true
    authResponseHeaders:
      - X-Auth-Request-User
      - X-Auth-Request-Email
      - X-Forwarded-Access-Token
      - X-Auth-Request-Access-Token
      - X-Atmosphere-Token
      - Authorization
    tls:
      insecureSkipVerify: true
---
# Source: {{ $fullName }}/templates/ingress_public_nginx.yaml
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ $fullName }}-rewrite
spec:
  stripPrefix:
    prefixes:
      - {{ .Values.publicApi.ingress.nginx.pathPrefix }}
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ $fullName }}-auth-errors
spec:
  errors:
    query: {{ .Values.publicApi.ingress.nginx.pathPrefix }}/oauth2/sign_out?rd=https://{{ .Values.publicApi.ingress.nginx.fqdn }}{url}
    service:
      name: oauth2-proxy-{{ $.Values.global.cp.instanceId }}
      port: 80
    status:
      - '401'
{{- end }}