# Copyright © 2023. Cloud Software Group, Inc.
# This file is subject to the license terms contained
# in the license file that is distributed with this file.

{{ if eq .Values.publicApi.ingress.controllerName "nginx" -}}
{{- $fullName := include "{{ $fullName }}.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/auth-response-headers: X-Auth-Request-User,X-Auth-Request-Email,X-Forwarded-Access-Token,X-Auth-Request-Access-Token,X-Atmosphere-Token
    nginx.ingress.kubernetes.io/auth-signin: https://{{ .Values.publicApi.ingress.nginx.fqdn }}{{ .Values.publicApi.ingress.nginx.pathPrefix }}/oauth2/start?rd=$escaped_request_uri
    nginx.ingress.kubernetes.io/auth-url: https://{{ .Values.publicApi.ingress.nginx.fqdn }}{{ .Values.publicApi.ingress.nginx.pathPrefix }}/oauth2/auth
    nginx.ingress.kubernetes.io/configuration-snippet: "auth_request_set $token $upstream_http_authorization;\nproxy_set_header
      Authorization $token;\nproxy_pass_header Authorization; \n"
    nginx.ingress.kubernetes.io/proxy-buffer-size: 16k
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/auth-snippet: |
      if ( $request_uri !~ "{{ .Values.publicApi.ingress.nginx.pathPrefix }}/(.*)" ) {
            return 200;
      }
    nginx.ingress.kubernetes.io/x-forwarded-prefix: {{ .Values.publicApi.ingress.nginx.pathPrefix }}
    nginx.ingress.kubernetes.io/use-regex: "true"
  name: {{ $fullName }}-public-nginx
spec:
  ingressClassName: {{ .Values.publicApi.ingress.nginx.className }}
  rules:
  - host: {{ .Values.publicApi.ingress.nginx.fqdn }}
    http:
      paths:
      - backend:
          service:
            name: {{ $fullName }}
            port:
              number: {{ $.Values.publicApiService.targetPort }}
        path: {{ .Values.publicApi.ingress.nginx.pathPrefix }}/(.*)
        pathType: Prefix
{{- end }}
{{ if eq .Values.publicApi.ingress.controllerName "traefik" -}}
{{- $fullName := include "bwprovisioner.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: {{ .Release.Namespace }}-{{ $fullName }}-auth-errors@kubernetescrd,{{ .Release.Namespace }}-{{ $fullName }}-auth@kubernetescrd,{{ .Release.Namespace }}-{{ $fullName }}-rewrite@kubernetescrd,{{ .Release.Namespace }}-{{ $fullName }}-auth-header@kubernetescrd
  name: {{ $fullName }}-public-traefik
spec:
  ingressClassName: traefik
  rules:
  - host: k8s-traefik-traefik-5bee87438a-d8c7af6f988c1544.elb.eu-west-2.amazonaws.com
    http:
      paths:
      - backend:
          service:
            name: {{ $fullName }}
            port:
              number: {{ $.Values.publicApiService.targetPort }}
        path: {{ .Values.publicApi.ingress.traefik.pathPrefix }}/
        pathType: Prefix
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ $fullName }}-auth
spec:
  forwardAuth:
    address: https://{{ .Values.publicApi.ingress.traefik.fqdn }}{{ .Values.publicApi.ingress.traefik.pathPrefix }}/oauth2/auth
    trustForwardHeader: true
    authResponseHeaders:
      - X-Auth-Request-User
      - X-Auth-Request-Email
      - X-Forwarded-Access-Token
      - X-Auth-Request-Access-Token
      - X-Atmosphere-Token
      - Authorization

---
# Source: {{ $fullName }}/templates/ingress_public_nginx.yaml
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ $fullName }}-auth-header
spec:
  headers:
    customRequestHeaders:
      X-Forwarded-Proto: "https"
      X-Forwarded-Host: {{ .Values.publicApi.ingress.traefik.fqdn }}
      X-Forwarded-Port: "443"
---
# Source: {{ $fullName }}/templates/ingress_public_nginx.yaml
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ $fullName }}-rewrite
spec:
  stripPrefix:
    prefixes:
      - {{ .Values.publicApi.ingress.traefik.pathPrefix }}
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ $fullName }}-auth-errors
spec:
  errors:
    status:
      - "401-403"
    service:
      name: oauth2-proxy-{{ $.Values.global.cp.instanceId }}
      port: 80
    query: "/oauth2/sign_in?rd={url}"
{{- end }}
