# Copyright © 2025. Cloud Software Group, Inc.
# This file is subject to the license terms contained
# in the license file that is distributed with this file.

{{- if eq .Values.ingress.controllerName "openshiftRouter" -}}
{{- $fullName := include "bwprovisioner.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    haproxy-ingress.github.io/headers: |
        X-Forwarded-Prefix: {{ .Values.publicApi.ingress.config.pathPrefix }}
        X-Forwarded-Host: {{ .Values.publicApi.ingress.config.fqdn }}
        X-Forwarded-Port: 443
        X-Forwarded-Proto: https
    haproxy-ingress.github.io/rewrite-target: /
    haproxy-ingress.github.io/config-backend: |
        http-response del-header x-auth-request-user
        http-response del-header x-auth-request-email
        http-response del-header x-auth-request-access-token
        http-response del-header X-Forwarded-Access-Token
        http-response del-header X-Atmosphere-Token
        http-response del-header gap-auth
     
    {{- with .Values.global.cp.resources.ingress.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  name: {{ $fullName }}-public-nginx
spec:
  ingressClassName: {{ .Values.publicApi.ingress.config.className }}
  rules:
  - host: {{ .Values.publicApi.ingress.config.fqdn }}
    http:
      paths:
      - backend:
          service:
            name: oauth2-proxy-{{ .Values.global.cp.instanceId }}
            port:
              number: 80
        pathType: Prefix
        path: /

{{- end }}
