# Copyright © 2023. Cloud Software Group, Inc.
# This file is subject to the license terms contained
# in the license file that is distributed with this file.

{{- $ingressHost := .Values.ingress.host | required ".Values.ingress.host is required." }}
{{ $cpHostname := (.Values.global.cp).cpHostname | required ".Values.global.cp.cpHostname is required." }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "common.names.fullname" . }}-wkc
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: backstage
    {{- include "tibcohub.platform.commonLabels" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: {{ .Release.Namespace }}-{{ include "common.names.fullname" . }}-header@kubernetescrd,{{ .Release.Namespace }}-{{ include "common.names.fullname" . }}-rewrite@kubernetescrd
spec:
  ingressClassName: {{ .Values.ingress.className | quote }}
  rules:
    - host: {{ $ingressHost }}
      http:
        paths:
          - backend:
              service:
                name: {{ include "common.names.fullname" . }}-wkc
                port:
                  number: 443
            path: /tibco/hub/.well-known/openid-configuration
            pathType: Exact
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ include "common.names.fullname" . }}-header
spec:
  headers:
    customRequestHeaders:
      X-Forwarded-Proto: "https"
      x-cp-host: {{ $cpHostname }}
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ include "common.names.fullname" . }}-rewrite
spec:
  replacePath:
    path: /.well-known/openid-configuration