# Copyright © 2025. Cloud Software Group, Inc.
# This file is subject to the license terms contained
# in the license file that is distributed with this file.

{{ if .Values.ingress.enabled -}}
{{- if eq .Values.ingress.controllerName "openshiftRouter" -}}
{{- $dot := . }}
{{- range $rule := .Values.ingress.rules -}}
{{- range $path := $rule.paths }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    haproxy-ingress.github.io/headers: |
        X-Forwarded-Prefix: {{ $path.path }}
    haproxy-ingress.github.io/rewrite-target: /
    {{- if $path.serviceDiscoverable }}
    platform.tibco.com/service-description: {{ $path.serviceDescription | squote }}
    {{- end }}
    {{- with $.Values.ingress.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    {{- include "dp-bwce-app.labels" $dot | nindent 4 }}
    platform.tibco.com/service-discoverable: {{ $path.serviceDiscoverable | quote }}
  name: {{ include "dp-bwce-app.fullname" $dot }}-{{ $path.port }}
spec:
  ingressClassName: haproxy
  rules:
  - host: {{ $rule.host | quote }}
    http:
      paths:
      - backend:
          service:
            name: {{ include "dp-bwce-app.fullname" $dot }}
            port:
              number: {{ $path.port }}
        pathType: Prefix
        path: {{ $path.path }}

{{- end }}
{{- end }}
{{- end }}
{{- end }}
